name: compass_app_riverpod
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  flutter_svg: ^2.2.1
  go_router: ^16.2.2
  google_fonts: ^6.3.1
  intl: ^0.20.2
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
